<?php $this->inlineScript()->captureStart(); ?>

$(function(){
    $('ul.sidebar-nav li ul li a.subjects').addClass('active');
});

<?php $this->inlineScript()->captureEnd(); ?>

<div class="content-header">
    <div class="header-section">
        <h1>
            <i class="hi hi-tasks"></i>Subjects<br>
            <small><?php echo $this->viewmodel()->getCurrent()->getChildren()[0]->subtitle; ?></small>
        </h1>
    </div>
</div>
<ul class="breadcrumb breadcrumb-top">
    <li>Home</li>
    <li><a href="">Subjects</a></li>
    <li><a href=""><?php echo $this->viewmodel()->getCurrent()->getChildren()[0]->subtitle; ?></a></li>
</ul>