<div class="block">
    <form class="form-horizontal" method="get" action="<?php echo $this->url('application/default', array('controller'=>'subject','action'=>'index'));?>">
        <div class="form-group">
            
            <div class="col-md-3">
            <input type="text" placeholder="Enter keyword.." class="form-control input-sm" name="keyword" id="keyword" value="<?=$this->filter['keyword'] ? $this->filter['keyword'] : ''?>">
            </div>
            
            <div class="col-md-2">
            <select class="form-control input-sm" name="active">
                <option value="">Status</option>
                <option value="1" <?php echo $this->filter['active']==='1' ? 'selected' : ''; ?>>Enabled</option>
                <option value="0" <?php echo $this->filter['active']==='0' ? 'selected' : ''; ?>>Disabled</option>
            </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3">
            <button class="btn btn-sm btn-primary" type="submit"><i class="fa fa-search"></i> Search</button>
            <?php if($this->layout()->getVariable('role')->hasPermission('subject_add')){ ?>
            <a class="btn btn-sm btn-success" href="<?php echo $this->url('application/default', array('controller'=>'subject','action'=>'add'));?>"><i class="fa fa-plus"></i> Add New</a>
            <?php } ?>
            </div>
        </div>
    </form>    
</div>
<div class="block">
    <!-- Responsive Full Content -->
    <div class="table-responsive">
        <table class="table table-vcenter table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Status</th>
                    <th>Blocked</th>
                    <th class="text-center" style="width: 150px;">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $item) { ?>
                <tr>
                    <td><a href="<?php echo $this->url('application/default', array('controller'=>'subject','action'=>'view','id'=>$item->id));?>"><?php echo $this->escapeHtml($item->name);?></a></td>
                    <td>
                        <?php if ($item->active) { ?>
                        <span class="label label-success">Enabled</span>
                        <?php } else { ?>
                        <span class="label label-default">Disabled</span>
                        <?php } ?>
                    </td>
                    <td>
                        <?php if ($item->blocked) { ?>
                        <span class="label label-success">Blocked</span>
                        <?php } else { ?>
                        <span class="label label-default">Unblocked</span>
                        <?php } ?>
                    </td>
                    <td class="text-center">
                        <div class="btn-group btn-group-xs">
                            <?php if($this->layout()->getVariable('role')->hasPermission('subject_view')){?>
			                     <a class="btn btn-default" title="" data-toggle="tooltip" href="<?php echo $this->url('application/default', array('controller'=>'subject','action'=>'view','id'=>$item->id));?>" data-original-title="View"><i class="fa fa-search"></i></a>
                            <?php }?>
                            <?php if($this->layout()->getVariable('role')->hasPermission('subject_edit')){?>
                                <a class="btn btn-primary <?php echo $item->blocked ? 'disabled': ''?>" title="" data-toggle="tooltip" href="<?php echo $this->url('application/default', array('controller'=>'subject','action'=>'edit','id'=>$item->id));?>" data-original-title="Edit"><i class="fa fa-pencil"></i></a>
                            <?php }?>
                            <?php if($this->layout()->getVariable('role')->hasPermission('subject_change-status')){?>
                                <?php if ($item->active) { ?>
                                    <a class="btn btn-danger" title="" data-toggle="tooltip" href="<?php echo $this->url('application/default', array('controller'=>'subject','action'=>'change-status','id'=>$item->id));?>" data-original-title="Disable"><i class="fa fa-times"></i></a>
                                <?php } else { ?>
                                    <a class="btn btn-success" title="" data-toggle="tooltip" href="<?php echo $this->url('application/default', array('controller'=>'subject','action'=>'change-status','id'=>$item->id));?>" data-original-title="Enable"><i class="fa fa-check"></i></a>
                                <?php } ?>
                            <?php }?>
                        </div>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <!-- END Responsive Full Content -->
    <div class="text-right">
        <?php 
            echo $this->paginationControl(
                // the paginator object
                $this->paginator,
                // the scrolling style
                'sliding',
                // the partial to use to render the control
                'partial/paginator.phtml',
                // the route to link to when a user clicks a control link
                array('query' => $this->filter)
            );
        ?>
    </div>
</div>