<div class="block">
    <?php if ($this->error) { ?>
        <div class="alert alert-danger alert-dismissable fade in">
            <button data-dismiss="alert" class="close" type="button">&times;</button>
            <i class="fa fa-times-circle"></i> <?php echo $this->error?>
        </div>
    <?php } ?>
    
    <!-- Horizontal Form Content -->
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); ?>
    
    <?php echo $this->partial('billing-details-fieldset', array('form' => $form)) ?>
    
    <div class="form-group form-actions">
        <div class="col-md-4 col-md-offset-3">
            <?php echo $this->formSubmit($form->get('submit'));?>
            <a class="btn btn-sm btn-warning" href="<?php echo $this->url('application/default',array('controller'=>'organization','action'=>'manage-billing-details'));?>"><i class="fa fa-repeat"></i> <?php echo $this->translate('Cancel'); ?></a>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <!-- END Horizontal Form Content -->
</div>

<?php $this->inlineScript()->appendFile('/modules/application/js/billing.js'); ?>

<?php $this->inlineScript()->captureStart(); ?>
$(function(){
    $('ul.sidebar-nav li a.billing-details').addClass('active');
});
<?php $this->inlineScript()->captureEnd(); ?>