<fieldset>
	<legend><?php echo $this->translate('Billing Details'); ?></legend>

    <div class="form-group">
        <label for="" class="col-md-3 control-label">
            <?php echo $this->translate('Address'); ?>
            <span class="text-danger">*</span>
        </label>
        <div class="col-md-4">
            <?php echo $this->formtext($form->get('address')); ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('address'), array('class'=>'list-unstyled text-danger'))?></div>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-md-3 control-label">
            <?php echo $this->translate('City'); ?>
            <span class="text-danger">*</span>
        </label>
        <div class="col-md-4">
            <?php echo $this->formtext($form->get('city')); ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('city'), array('class'=>'list-unstyled text-danger'))?></div>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-md-3 control-label">
            <?php echo $this->translate('Country'); ?>
            <span class="text-danger">*</span>
        </label>
        <div class="col-md-4">
            <?php echo $this->formselect($form->get('id_country')->setOptions(array('empty_option'=>$this->translate('Please choose a Country')))); ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('id_country'), array('class'=>'list-unstyled text-danger'))?></div>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-md-3 control-label">
            <?php echo $this->translate('State / Province'); ?>
            <span class="text-danger">*</span>
        </label>
        <div class="col-md-4">
            <input type="hidden" id="selected_state" value="<?php echo $form->get('id_state')->getValue(); ?>" />
            <?php echo $this->formselect($form->get('id_state')->setOptions(array('empty_option'=>$this->translate('Please choose a State / Province')))); ?>
            <div class="help-block">
            <span class="loading-states" style="display:none;"><i class="fa fa-spin fa-spinner"></i> <?php echo $this->translate('Loading country states / provinces'); ?>...</span>
            <?=$this->formElementErrors($form->get('id_state'), array('class'=>'list-unstyled text-danger'))?>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-md-3 control-label">
            <?php echo $this->translate('Zip / Postcode'); ?>
            <span class="text-danger">*</span>
        </label>
        <div class="col-md-4">
            <?php echo $this->formtext($form->get('postcode')); ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('postcode'), array('class'=>'list-unstyled text-danger'))?></div>
        </div>
    </div>
</fieldset>
<fieldset>
	<legend><?php echo $this->translate('Credit Card Details'); ?></legend>
	<div class="form-group">

		<div class="col-md-4 col-md-offset-3"><p class="text-warning form-control-static"><i class="fa fa-info-circle"></i> 

			<?php 
				if ($country == 'Poland') {
				echo $this->translate('Your credit card details are stored safely with PayU');

				} else {

				echo $this->translate('Your credit card details are stored safely with PayPal');

				}
			?>

		</p></div>
	</div>
	<div class="form-group">
        <label for="" class="col-md-3 control-label">
            <?php echo $this->translate('Type'); ?>
            <span class="text-danger">*</span>
        </label>
        <div class="col-md-4">
            <?php echo $this->formselect($form->get('cardtype')); ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('cardtype'), array('class'=>'list-unstyled text-danger'))?></div>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-md-3 control-label">
            <?php echo $this->translate('Card Number'); ?>
            <span class="text-danger">*</span>
        </label>
        <div class="col-md-4">
            <?php echo $this->formtext($form->get('cardnumber')); ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('cardnumber'), array('class'=>'list-unstyled text-danger'))?></div>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-md-3 control-label">
            <?php echo $this->translate('Cvv2'); ?>
            <span class="text-danger">&nbsp;</span>
        </label>
        <div class="col-md-4">
            <?php echo $this->formtext($form->get('cvv2')); ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('cvv2'), array('class'=>'list-unstyled text-danger'))?></div>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-md-3 control-label">
            <?php echo $this->translate('Expiration'); ?>
            <span class="text-danger">*</span>
        </label>
        <div class="col-md-4">
            <div class="form-inline">
                <div class="form-group">
                    <?php echo $this->formtext($form->get('exp_month')); ?>
                    <div class="help-block"><?=$this->formElementErrors($form->get('exp_month'), array('class'=>'list-unstyled text-danger'))?></div>
                </div>
                <div class="form-group">
                    <?php echo $this->formtext($form->get('exp_year')); ?>
                    <div class="help-block"><?=$this->formElementErrors($form->get('exp_year'), array('class'=>'list-unstyled text-danger'))?></div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="col-md-3 control-label">
            <?php echo $this->translate('Cardholder Name'); ?>
            <span class="text-danger">*</span>
        </label>
        <div class="col-md-4">
            <?php echo $this->formtext($form->get('cardholder_name')); ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('cardholder_name'), array('class'=>'list-unstyled text-danger'))?></div>
        </div>
    </div>
</fieldset>