<div class="block">
    <!-- Horizontal Form Title -->
    <div class="block-title">
        <h2><strong>Organization</strong> Form</h2>
    </div>
    <!-- END Horizontal Form Title -->
    
    <?php if ($this->error) { ?>
    <div class="alert alert-danger alert-dismissable">
        <button data-dismiss="alert" class="close" type="button">&times;</button>
        <h4><i class="fa fa-times-circle"></i> Error</h4> <?php echo $this->error?>
    </div>
    <?php } ?>

    <!-- Horizontal Form Content -->
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); echo $this->formHidden($form->get('id')); ?>
        <div class="form-group">
            <label for="" class="col-md-3 control-label">
                Organization
                <span class="text-danger">*</span>
            </label>
            <div class="col-md-9">
                <?php echo $this->formInput($form->get('name')); ?>
                <div class="help-block"><?=$this->formElementErrors($form->get('name'), array('class'=>'list-unstyled text-danger'))?></div>
            </div>
        </div>
        
        <div class="form-group form-actions">
            <div class="col-md-9 col-md-offset-3">
                <?php echo $this->formSubmit($form->get('submit'));?>
                <a class="btn btn-sm btn-warning" href="<?php echo $this->url('application/default', array('controller'=>'organization','action'=>'index'));?>"><i class="fa fa-repeat"></i> Return</a>
            </div>
        </div>
    <?php echo $this->form()->closeTag(); ?>
    <!-- END Horizontal Form Content -->
</div>