<div class="block">
    <!-- Info Content -->
    
    <?php if ($m==1) { ?>
        <div class="alert alert-success alert-dismissable">
            <button data-dismiss="alert" class="close" type="button">&times;</button>
            <i class="fa fa-check-circle"></i> <?php echo $this->translate('Billing details added successfully!'); ?>
        </div>
    <?php } ?>
    
    <?php if (!is_null($entity)) { ?>
    <fieldset>
    	<legend><?php echo $this->translate('Billing Details')?></legend>
        <table class="table table-borderless table-striped">
            <tbody>
                <tr>
                    <td style="width: 20%;"><strong><?php echo $this->translate('Address'); ?></strong></td>
                    <td><?php echo $entity->address; ?></td>
                </tr>
                <tr>
                    <td style="width: 20%;"><strong><?php echo $this->translate('City'); ?></strong></td>
                    <td><?php echo $entity->city; ?></td>
                </tr>
                <tr>
                    <td style="width: 20%;"><strong><?php echo $this->translate('Country'); ?></strong></td>
                    <td><?php echo $entity->country; ?></td>
                </tr>
                <tr>
                    <td style="width: 20%;"><strong><?php echo $this->translate('State'); ?></strong></td>
                    <td><?php echo $entity->state; ?></td>
                </tr>
                <tr>
                    <td style="width: 20%;"><strong><?php echo $this->translate('Zip / Postcode'); ?></strong></td>
                    <td><?php echo $entity->postcode; ?></td>
                </tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset>
    	<legend><?php echo $this->translate('Credit Card Details')?> <h6 class="text-muted"><i class="fa fa-info-circle"></i> <?php echo $this->translate('Your credit card details are stored safely with PayPal'); ?></h6></legend>
        <table class="table table-borderless table-striped">
            <tbody>
                <tr>
                    <td style="width: 20%;"><strong><?php echo $this->translate('Type'); ?></strong></td>
                    <td><?php echo $entity->cardtype; ?></td>
                </tr>
                <tr>
                    <td style="width: 20%;"><strong><?php echo $this->translate('Card Number'); ?></strong></td>
                    <td><?php echo $entity->cardnumber; ?></td>
                </tr>
                <tr>
                    <td style="width: 20%;"><strong><?php echo $this->translate('Expiration'); ?></strong></td>
                    <td><?php echo $entity->exp_month.'/'.$entity->exp_year; ?></td>
                </tr>
                <tr>
                    <td style="width: 20%;"><strong><?php echo $this->translate('Cardholder Name'); ?></strong></td>
                    <td><?php echo $entity->cardholder_name; ?></td>
                </tr>
            </tbody>
        </table>
    </fieldset>
    <?php } else { ?>
    <p><?php echo sprintf($this->translate('We could not find any billing details attached to your organization. Please press <a href="%s" class="text-info">here</a> to add a new billing detail.'), $this->url('application/default', array('controller'=>'organization','action'=>'add-billing-details'))); ?></p>
    <?php } ?>
    <!-- END Info Content -->
</div>

<?php if($this->layout()->getVariable('role')->hasPermission('organization_add-billing-details')){?>
<div class="block full">
	<div class="row">
		<div class="col-md-12">
            <a href="<?php echo $this->url('application/default', array('controller'=>'organization','action'=>'add-billing-details'));?>" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> <?php echo $this->translate('Add New Billing Details'); ?></a>
		</div>
	</div>
</div>
<?php }?>

<?php $this->inlineScript()->captureStart(); ?>
$(function(){
    $('ul.sidebar-nav li a.billing-details').addClass('active');
});
<?php $this->inlineScript()->captureEnd(); ?>