<section class="site-section site-section-light site-section-top themed-background-dark">
    <div class="container">
        <h1 class="text-center animation-slideDown"><i class="fa fa-arrow-right"></i> <strong><?php echo $this->translate('Sign Up'); ?></strong></h1>
        <h2 class="h3 text-center animation-slideUp"><?php echo $this->translate('Set your password to start working!');?></h2>
    </div>
</section>            

<section class="site-content site-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-4 site-block">

<?php 
$form->prepare();
$form->setAttribute('class', 'form-horizontal');
echo $this->form()->openTag($form);
?>
<?php if (!empty($messages)) { ?>
<div class="form-group">
    <div class="col-xs-12">
        <div class="alert alert-danger">
        <?php echo $messages; ?>
        </div>
    </div>
</div>
<?php } ?>

<div class="form-group">
    <div class="col-xs-12">
        <div class="input-group">
            <span class="input-group-addon"><i class="gi gi-keys"></i></span>
            <?php echo $this->formInput($form->get('password')->setAttribute('class','form-control input-lg')); ?>
        </div>
        <div class="help-block"><?=$this->formElementErrors($form->get('password'), array('class'=>'list-unstyled text-danger'))?></div>
    </div>
</div>
<div class="form-group">
    <div class="col-xs-12">
        <div class="input-group">
            <span class="input-group-addon"><i class="gi gi-keys"></i></span>
            <?php 
            echo $this->formInput($form->get('confirm-password')->setAttribute('class','form-control input-lg')); ?>
        </div>
        <div class="help-block"><?=$this->formElementErrors($form->get('confirm-password'), array('class'=>'list-unstyled text-danger'))?></div>
    </div>
</div>
<div class="form-group form-actions">
    <div class="col-xs-12 text-right">
        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-angle-right"></i> <?php echo $this->translate('Confirm Password'); ?></button>
    </div>
</div>
 
<div class="form-group">
    <div class="col-md-12 text-center">
        <a href="<?php echo $this->url('login');?>" id="link-reminder-login"><small><?php echo $this->translate('Already have a password? Login'); ?></small></a> 
    </div>
</div>
<div class="clearfix">&nbsp;</div>
<?php echo $this->form()->closeTag(); ?>            
            </div>
        </div>
        <hr>
    </div>
</section>

