<!-- Google Code for Registro Conversion Page -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 878557986;
    var google_conversion_language = "en";
    var google_conversion_format = "3";
    var google_conversion_color = "ffffff";
    var google_conversion_label = "8FVRCNOSgmoQovb2ogM";
    var google_remarketing_only = false;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
    <div style="display:inline;">
    <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/878557986/?label=8FVRCNOSgmoQovb2ogM&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>
<section class="site-section site-section-light site-section-top themed-background-dark">
    <div class="container">
        <h1 class="text-center animation-slideDown"><i class="fa fa-check"></i> <strong><?php echo $this->translate('Successful Registration'); ?></strong></h1>
        <h2 class="h3 text-center animation-slideUp"><?php echo $this->translate('Get your own dashboard in a few seconds!');?></h2>
    </div>
</section>            

<section class="site-content site-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-6  col-lg-12  site-block">
                
<h3 class="h2 site-heading "><?php echo $this->translate('Your Account Has Been Created!'); ?></h3>

<p><?php echo $this->translate('Congratulations! Your new account has been successfully created!')?></p> 
<p><?php echo $this->translate('You can now start working towards excellence!')?></p> 
<p><?php echo $this->translate('If you have ANY questions about the operation of this app, please e-mail us at support@quickaudits.io.')?></p> 
<p><?php echo $this->translate('A confirmation has been sent to the provided e-mail address. If you have not received it within the hour, please contact us at support@quickaudits.io')?>.</p>

            </div>
        </div>
        <hr>
    </div>
</section>