<section class="site-section site-section-light site-section-top themed-background-dark">
    <div class="container">
        <h1 class="text-center animation-slideDown"><i class="fa fa-check"></i> <strong><?php echo $this->translate('Successful Operation'); ?></strong></h1>
        
    </div>
</section>            

<section class="site-content site-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-6  col-lg-12  site-block">
                
<h3 class="h2 site-heading "><?php echo $this->translate('Your Password Has Been Updated!'); ?></h3>

<p><?php echo $this->translate(sprintf('Your password was changed successfully. Now it is time to <a href="%s">Login</a>', $this->url('login'))); ?></p> 

            </div>
        </div>
        <hr>
    </div>
</section>

