<section class="site-section site-section-light site-section-top themed-background-dark">
    <div class="container">
        <h1 class="text-center animation-slideDown"><i class="fa fa-arrow-right"></i> <strong><?php echo $this->translate('Login'); ?></strong></h1>
        <h2 class="h3 text-center animation-slideUp"><?php echo $this->translate('Start working towards excellence!');?></h2>
    </div>
</section>            

<section class="site-content site-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-4 site-block">

<?php $form->prepare(); echo $this->form()->openTag($form); ?>
<?php if (!empty($error)) { ?>
<div class="form-group">
    <div class="col-xs-12">
        <div class="alert alert-danger">
        <h4><i class="fa fa-times-circle"></i> <?php echo $this->translate('Error'); ?></h4> <?php echo $error; ?>
        </div>
    </div>
</div>
<?php } ?>
<div class="form-group">
    <div class="col-xs-12">
        <div class="input-group">
            <span class="input-group-addon"><i class="gi gi-keys"></i></span>
            <?php  echo $this->formInput($form->get('password')); ?>
        </div>
        <div class="help-block"><?=$this->formElementErrors($form->get('password'), array('class'=>'list-unstyled text-danger'))?></div>
    </div>
</div>
<div class="form-group">
    <div class="col-xs-12">
        <div class="input-group">
            <span class="input-group-addon"><i class="gi gi-keys"></i></span>
            <?php  echo $this->formInput($form->get('confirm-password')); ?>
        </div>
        <div class="help-block"><?=$this->formElementErrors($form->get('confirm-password'), array('class'=>'list-unstyled text-danger'))?></div>
    </div>
</div>
<div class="form-group form-actions">
    <div class="col-xs-8 text-right">
        <?php echo $this->formsubmit($form->get('reset'));?>
    </div>
</div>
<div class="form-group">
    <div class="col-xs-12 text-center">
        <a href="<?php echo $this->url('login');?>" id="link-reminder-login"><small><?php echo $this->translate('Did you remember your password? Login'); ?></small></a>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>            
                
            </div>
        </div>
        <hr>
    </div>
</section>