<div class="content-header">
    <div class="header-section">
        <h1>
            <i class="gi gi-charts"></i><?php echo $this->translate('Reports'); ?><br>
            <small><?php echo $this->viewmodel()->getCurrent()->getChildren()[0]->subtitle; ?></small>
        </h1>
    </div>
</div>
<ul class="breadcrumb breadcrumb-top">
    <li><?php echo $this->translate('Home'); ?></li>
    <li><?php echo $this->translate('Reports'); ?></li>
    <li><a href=""><?php echo $this->viewmodel()->getCurrent()->getChildren()[0]->subtitle; ?></a></li>
</ul>