<?php $projectsScores = array(); ?>
<?php foreach ($this->paginator as $item) { ?>
<?php $projectsScores[$item->id_project] = array('score'=>$item->score,'samples'=>$item->samples); ?>
<?php } ?>

<div class="block ">
    <form class="form-horizontal" method="get" action="<?php echo $this->url('application/default', array('controller'=>'report','action'=>'project-overview'));?>">
        
        <div class="form-group">
            <div class="col-md-3">
            <select class="form-control input-sm select-chosen" name="project[]" data-placeholder="All Projects" multiple>
                <?php foreach ($projects as $item) { ?>
                <option value="<?php echo $item->id; ?>" <?php echo isset($this->filter['project']) && in_array($item->id, $this->filter['project']) ? 'selected' : ''; ?>><?php echo $item->name; ?></option>
                <?php } ?>
            </select>
            </div>
            
            <div class="col-md-2">
            <select class="form-control input-sm select-chosen" name="channel[]" data-placeholder="All Channels" multiple>
                <?php foreach ($channels as $item) { ?>
                <option value="<?php echo $item->id; ?>" <?php echo isset($this->filter['channel']) && in_array($item->id, $this->filter['channel']) ? 'selected' : ''; ?>><?php echo $item->name; ?></option>
                <?php } ?>
            </select>
            </div>
            
            <div class="col-md-2">
            <select class="form-control input-sm select-chosen" name="language[]" data-placeholder="All Languages" multiple>
                <?php foreach ($languages as $item) { ?>
                <option value="<?php echo $item->id; ?>" <?php echo isset($this->filter['language']) && in_array($item->id, $this->filter['language']) ? 'selected' : ''; ?>><?php echo $item->name; ?></option>
                <?php } ?>
            </select>
            </div>
            
            <div class="col-md-3">
            <div class="input-group input-daterange" data-date-format="mm/dd/yyyy">
                <input type="text" id="date_from" name="date_from" class="form-control text-center" placeholder="From" value="<?php echo $this->filter['date_from']; ?>">
                <span class="input-group-addon"><i class="fa fa-angle-right"></i></span>
                <input type="text" id="date_to" name="date_to" class="form-control text-center" placeholder="To" value="<?php echo $this->filter['date_to']; ?>">
            </div>
            </div>

            <div class="col-md-1">
            <button class="btn btn-sm btn-primary" type="submit"><i class="fa fa-search"></i> Search</button>
            </div>

            
        </div>
    </form>    
</div>

<div class="block full">
    <!-- Bars Chart Title -->
    <div class="block-title">
        <h2>Projects Overview</h2>
    </div>
    <!-- END Bars Chart Title -->

    <!-- Bars Chart Content -->
    <!-- Flot Charts (initialized in js/pages/compCharts.js), for more examples you can check out http://www.flotcharts.org/ -->
    <div id="chart-bars" class="chart"></div>
    <!-- END Bars Chart Content -->
</div>

<div class="block full">
    <!-- Responsive Full Content -->
    <div class="table-responsive">
        <table class="table table-vcenter table-striped report">
            <thead>
                <tr>
                    <th>Project / Group</th>
                    <?php foreach ($questionsGroups as $questionGroup){ ?>
                    <th><?php echo $questionGroup->name; ?></th>
                    <?php } ?>
                    <th>Grand Total</th>
                    <th>Samples</th>
                    <th class="text-center" style="width: 50px;">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                
                <?php $newProjectsGroupsScores = $projectsGroupsScores->current(); ?>
                
                <?php while ($newProjectsGroupsScores) { ?>
                <?php $oldProjectsGroupsScores = $newProjectsGroupsScores; ?>
                <tr>
                    <td><?php echo $newProjectsGroupsScores->project; ?></td>
                    <?php while ($newProjectsGroupsScores && $newProjectsGroupsScores->id_project==$oldProjectsGroupsScores->id_project) { ?>
                    <td><?php echo $newProjectsGroupsScores->score; ?></td>
                    <?php $projectsGroupsScores->next(); ?>
                    <?php $newProjectsGroupsScores = $projectsGroupsScores->current(); ?>
                    <?php } ?>
                    <td><?php echo $projectsScores[$oldProjectsGroupsScores->id_project]['score']; ?></td>
                    <td><?php echo $projectsScores[$oldProjectsGroupsScores->id_project]['samples']; ?></td>
                    <td class="text-center">
                        <div class="btn-group btn-group-xs">
                            <?php $newFilter = $filter; ?>
                            <?php $newFilter['project'] = $oldProjectsGroupsScores->id_project; ?>
                            <?php unset($newFilter['organization']); ?>
                            <a class="btn btn-default" title="" data-toggle="tooltip" href="<?php echo $this->url('application/default', array('controller'=>'report','action'=>'project-detail'));?>?<?php echo http_build_query($newFilter); ?>" data-original-title="View"><i class="fa fa-search"></i></a>
                        </div>
                    </td>
                </tr>
                <?php } ?>
                
            </tbody>
        </table>
    </div>
    <!-- END Responsive Full Content -->
    <div class="text-right">
        <?php 
            echo $this->paginationControl(
                // the paginator object
                $this->paginator,
                // the scrolling style
                'sliding',
                // the partial to use to render the control
                'partial/paginator.phtml',
                // the route to link to when a user clicks a control link
                array('query' => $this->filter)
            );
        ?>
    </div>
</div>

<?php $this->inlineScript()->captureStart(); ?>

$(function(){
    $('ul.sidebar-nav li ul li a.projects-overview').addClass('active');
    <?php $data = array(); ?>
    <?php foreach ($this->paginator as $item) { ?>
    <?php array_push($data, '["'.$item->project.'", '.$item->score.']'); ?>
    <?php } ?>
    
	    
	var data = [ <?php echo implode(', ', $data); ?> ];
    
	$.plot($('#chart-bars'), [ data ], {
    	series: {
            bars: {
                show: true, 
                barWidth: 0.6, 
                align: "center", 
                lineWidth: 0, 
                fillColor: {
                   colors: [{opacity: 0.5}, {opacity: 0.5}]
                }
            },
            valueLabels: { show: true }
    	},
    	grid: {borderWidth: 0},
    	colors: ['#9b59b6'],
    	xaxis: {
    		mode: "categories",
    		tickLength: 0
    	}
    });
    
});

<?php $this->inlineScript()->captureEnd(); ?>