<div class="block">
    <?php if ($this->error) { ?>
    <div class="alert alert-danger alert-dismissable fade in">
        <button data-dismiss="alert" class="close" type="button">&times;</button>
        <i class="fa fa-times-circle"></i> <?php echo $this->error?>
    </div>
    <?php } ?>
    
    <!-- Horizontal Form Content -->
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <label class="col-md-3 control-label"><?php echo $this->translate('Project'); ?> <span class="text-danger">*</span></label>
            <div class="col-md-9">
                <?php echo $this->formselect($form->get('id_project')->setOptions(array('empty_option'=>$this->translate('Select a Project')))); ?>
                <div class="help-block"><?=$this->formElementErrors($form->get('id_project'), array('class'=>'list-unstyled text-danger'))?></div>
            </div>
        </div>
    
        <div class="form-group">
            <label class="col-md-3 control-label"><?php echo $this->translate('Role'); ?> <span class="text-danger">*</span></label>
            <div class="col-md-9">
                <?php echo $this->formselect($form->get('id_project_role')->setOptions(array('empty_option'=>$this->translate('Select a Role')))); ?>
                <div class="help-block"><?= $this->formElementErrors($form->get('id_project_role'), array('class'=>'list-unstyled text-danger'))?></div>
            </div>
        </div>
        
        <div class="form-group form-actions">
            <div class="col-md-9 col-md-offset-3">
                <?php echo $this->formSubmit($form->get('submit'));?>
                <a class="btn btn-sm btn-warning" href="<?php echo $this->url('application/default', array('controller'=>'user','action'=>'edit','id'=>$id));?>"><i class="fa fa-repeat"></i> <?php echo $this->translate('Return'); ?></a>
            </div>
        </div>
    <?php echo $this->form()->closeTag(); ?>
    <!-- END Horizontal Form Content -->
</div>