<div class="block">
    <?php if ($this->error) { ?>
    <div class="alert alert-danger alert-dismissable">
        <button data-dismiss="alert" class="close" type="button">&times;</button>
        <h4><i class="fa fa-times-circle"></i> <?php echo $this->translate('Error'); ?></h4> <?php echo $this->error?>
    </div>
    <?php } ?>
    
    <!-- Horizontal Form Content -->
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); echo $this->formHidden($form->get('id')); ?>
        <div class="form-group">
            <label for="" class="col-md-3 control-label">
                <?php echo $this->translate('Name'); ?>
                <span class="text-danger">*</span>
            </label>
            <div class="col-md-9">
                <?php echo $this->formInput($form->get('name')->setAttributes(array('placeholder'=>$this->translate('Enter user full name')))); ?>
                <div class="help-block"><?=$this->formElementErrors($form->get('name'), array('class'=>'list-unstyled text-danger'))?></div>
            </div>
        </div>
                
        <div class="form-group">
            <label for="" class="col-md-3 control-label">
                <?php echo $this->translate('Email'); ?>
                <span class="text-danger">*</span>
            </label>
            <div class="col-md-9">
                <?php echo $this->formInput($form->get('email')); ?>
                <div class="help-block"><?=$this->formElementErrors($form->get('email'), array('class'=>'list-unstyled text-danger'))?></div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label"><?php echo $this->translate('Role'); ?> <span class="text-danger">*</span></label>
            <div class="col-md-9">
                <?php echo $this->formselect($form->get('id_role')->setOptions(array('empty_option'=>$this->translate('Select a Role')))); ?>
                <div class="help-block"><?= $this->formElementErrors($form->get('id_role'), array('class'=>'list-unstyled text-danger'))?></div>
            </div>
        </div>
        <!-- 
        <div class="form-group">
            <label class="col-md-3 control-label">Languages <span class="text-danger">*</span></label>
            <div class="col-md-9">
                <?php echo $this->formselect($form->get('id_language')); ?>
                <div class="help-block"><?=$this->formElementErrors($form->get('id_language'), array('class'=>'list-unstyled text-danger'))?></div>
            </div>
        </div>
        -->
        <fieldset>
            <legend><?php echo $this->translate('Project Credentials'); ?></legend>
            <div class="form-group">
                <label class="col-md-3 control-label"><?php echo $this->translate('Project'); ?> <span class="text-danger">*</span></label>
                <div class="col-md-9">
                    <?php echo $this->formselect($form->get('id_project')); ?>
                    <div class="help-block"><?=$this->formElementErrors($form->get('id_project'), array('class'=>'list-unstyled text-danger'))?></div>
                </div>
            </div>
        
            <div class="form-group">
                <label class="col-md-3 control-label"><?php echo $this->translate('Role'); ?> <span class="text-danger">*</span></label>
                <div class="col-md-9">
                    <?php echo $this->formselect($form->get('id_project_role')); ?>
                    <div class="help-block"><?= $this->formElementErrors($form->get('id_project_role'), array('class'=>'list-unstyled text-danger'))?></div>
                </div>
            </div>
        </fieldset>
        <div class="form-group form-actions">
            <div class="col-md-9 col-md-offset-3">
                <?php echo $this->formSubmit($form->get('submit'));?>
                <a class="btn btn-sm btn-warning" href="<?php echo $this->url('application/default', array('controller'=>'user','action'=>'index'));?>"><i class="fa fa-repeat"></i> <?php echo $this->translate('Return'); ?></a>
            </div>
        </div>        
    <?php echo $this->form()->closeTag(); ?>
    <!-- END Horizontal Form Content -->
</div>