<div class="block">
    <!-- Horizontal Form Content -->
    <?php $form->prepare(); ?>
    <?php 
    echo $this->form()->openTag($form); 
    echo $this->formHidden($form->get('id'));
    ?>
        <div class="form-group">
            <label for="" class="col-md-3 control-label">
                <?php echo $this->translate('Password'); ?>
                <span class="text-danger">*</span>
            </label>
            <div class="col-md-9">
                <?php echo $this->formpassword($form->get('password')->setAttributes(array('placeholder'=>$this->translate('Enter new password')))); ?>
                <div class="help-block"><?=$this->formElementErrors($form->get('password'), array('class'=>'list-unstyled text-danger'))?></div>
            </div>
        </div>
        
        <div class="form-group">
            <label for="" class="col-md-3 control-label">
                <?php echo $this->translate('Confirm Password'); ?>
                <span class="text-danger">*</span>
            </label>
            <div class="col-md-9">
                <?php echo $this->formpassword($form->get('confirm-password')->setAttributes(array('placeholder'=>$this->translate('Confirm new password')))); ?>
                <div class="help-block"><?=$this->formElementErrors($form->get('confirm-password'), array('class'=>'list-unstyled text-danger'))?></div>
            </div>
        </div>
        
        <div class="form-group form-actions">
            <div class="col-md-9 col-md-offset-3">
                <?php echo $this->formSubmit($form->get('submit'));?>
                <a class="btn btn-sm btn-warning" href="<?php echo $this->url('application/default', array('controller'=>'user','action'=>'index'));?>"><i class="fa fa-repeat"></i> <?php echo $this->translate('Return'); ?></a>
            </div>
        </div>
    <?php echo $this->form()->closeTag(); ?>
    <!-- END Horizontal Form Content -->
</div>