<!DOCTYPE html>
<!--[if IE 8]>         
<html class="no-js lt-ie9"> <![endif]-->
<!--[if IE 9]>         
<html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js"> 
<!--<![endif]-->
    <head>
        <meta charset="utf-8">

        <title>Quick Audits</title>

        <meta name="description" content="">
        <meta name="author" content="Clickway Software IT">
        <meta name="robots" content="noindex, nofollow">

        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

        <!-- Icons -->
        <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
        <link rel="shortcut icon" href="<?=$this->basePath('/modules/application/')?>img/favicon.ico">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon57.png" sizes="57x57">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon72.png" sizes="72x72">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon76.png" sizes="76x76">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon114.png" sizes="114x114">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon120.png" sizes="120x120">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon144.png" sizes="144x144">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon152.png" sizes="152x152">
        <!-- END Icons -->

        <!-- Stylesheets -->
        <!-- Bootstrap is included in its original form, unaltered -->
        <link rel="stylesheet" href="<?=$this->basePath('/modules/application/')?>css/bootstrap.min.css">

        <!-- Related styles of various icon packs and plugins -->
        <link rel="stylesheet" href="<?=$this->basePath('/modules/application/')?>css/plugins.css">

        <!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
        <link rel="stylesheet" href="<?=$this->basePath('/modules/application/')?>css/main.css">

        <!-- Include a specific file here from css/themes/ folder to alter the default theme of the template -->

        <!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
        <link rel="stylesheet" href="<?=$this->basePath('/modules/application/')?>css/themes.css">
        <!-- CUSTOM ICONS QUICK AUDITS -->
        <link rel="stylesheet" href="<?=$this->basePath('/modules/application/')?>css/icons.css">
        <!-- END Stylesheets -->
        <link rel="stylesheet" href="<?=$this->basePath('/modules/application/')?>css/register.css">

        <!-- Modernizr (browser feature detection library) & Respond.js (Enable responsive CSS code on browsers that don't support it, eg IE8) -->
        <script src="<?=$this->basePath('/modules/application/')?>js/vendor/modernizr-2.7.1-respond-1.4.2.min.js"></script>
    </head>
    <body>
        <!-- Login Alternative Row -->
        <div class="container">
        
            <div class="row">
                <div class="col-md-6 col-xs-8 col-md-offset-3 col-xs-offset-2">
                    <!-- Login Container -->
                    <div id="login-container">
                        <!-- Login Title -->
                        <div class="login-title text-center">
                            <img alt="" src="<?=$this->basePath('/img/logo-qa.png')?>" class="" />
                        </div>
                        <!-- END Login Title -->
                        <!-- Login Block -->
                        <div class="block push-bit">
        
                            <?php echo $this->content; ?>
                            
                        </div>
                        <!-- END Login Block -->
                    </div>
                    <!-- END Login Container -->
                </div>
            </div>
            
        </div>
        <!-- END Login Alternative Row -->
        

        <!-- Include Jquery library from Google's CDN but if something goes wrong get Jquery from local file (Remove 'https:' if you have SSL) -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script>!window.jQuery && document.write(decodeURI('%3Cscript src="<?=$this->basePath('/modules/application/')?>js/vendor/jquery-1.11.1.min.js"%3E%3C/script%3E'));</script>

        <!-- Bootstrap.js, Jquery plugins and Custom JS code -->
        <?php
        echo $this->inlineScript()->prependFile($this->basePath('/modules/application/js/vendor/bootstrap.min.js'))
                                  ->prependFile($this->basePath('/modules/application/js/plugins.js'))
                                  ->prependFile($this->basePath('/modules/application/js/app.js'))
                                  ->prependFile($this->basePath('/modules/application/js/pages/login.js'));
        ?>
        <script>$(function(){ Login.init(); });</script>
    </body>
</html>