<!DOCTYPE html>
<!--[if IE 8]>         
<html class="no-js lt-ie9"> <![endif]-->
<!--[if IE 9]>         
<html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js"> 
<!--<![endif]-->
    <head>
        <meta charset="utf-8">

        <title>Quick Audits</title>

        <meta name="description" content="">
        <meta name="author" content="Clickway Software IT">
        <meta name="robots" content="noindex, nofollow">

        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

        <!-- Icons -->
        <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
        <link rel="shortcut icon" href="<?=$this->basePath('/modules/application/')?>img/favicon.ico">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon57.png" sizes="57x57">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon72.png" sizes="72x72">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon76.png" sizes="76x76">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon114.png" sizes="114x114">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon120.png" sizes="120x120">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon144.png" sizes="144x144">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/modules/application/')?>img/icon152.png" sizes="152x152">
        <!-- END Icons -->

        <!-- Stylesheets -->
        <!-- Bootstrap is included in its original form, unaltered -->
        <link rel="stylesheet" href="<?=$this->basePath('/modules/application/')?>css/bootstrap.min.css">

        <!-- Related styles of various icon packs and plugins -->
        <link rel="stylesheet" href="<?=$this->basePath('/modules/application/')?>css/plugins.css">

        <!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
        <link rel="stylesheet" href="<?=$this->basePath('/modules/application/')?>css/main-login.css">

        <!-- Include a specific file here from css/themes/ folder to alter the default theme of the template -->

        <!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
        <link rel="stylesheet" href="<?=$this->basePath('/modules/application/')?>css/themes.css">
        <!-- END Stylesheets -->
        
        <link rel="stylesheet" href="<?=$this->basePath('/modules/application/')?>css/register.css">

        <!-- Modernizr (browser feature detection library) & Respond.js (Enable responsive CSS code on browsers that don't support it, eg IE8) -->
        <script src="<?=$this->basePath('/modules/application/')?>js/vendor/modernizr-2.7.1-respond-1.4.2.min.js"></script>
    </head>
    <body>

        <!-- Page Container -->
        <!-- In the PHP version you can set the following options from inc/config file -->
        <!-- 'boxed' class for a boxed layout -->
        <div id="page-container">
            <!-- Site Header -->
            <header>
                <div class="container">
                    <!-- Site Logo -->
                    <a href="https://www.quickaudits.io" class="site-logo">
                        <img src="<?=$this->basePath('/img/logo-qa-white.png')?>" class="">
                    </a>
                    <!-- Site Logo -->

                    <!-- Site Navigation -->
                    <nav>
                        <!-- Menu Toggle -->
                        <!-- Toggles menu on small screens -->
<!--                         <a href="javascript:void(0)" class="btn btn-default site-menu-toggle visible-xs visible-sm"> -->
<!--                             <i class="fa fa-bars"></i> -->
<!--                         </a> -->
                        <!-- END Menu Toggle -->

                        <!-- Main Menu -->
                        <ul class="site-nav">
                            <!-- Toggles menu on small screens -->
                            <li class="visible-xs visible-sm">
                                <a href="javascript:void(0)" class="site-menu-toggle text-center">
                                    <i class="fa fa-times"></i>
                                </a>
                            </li>
                            <!-- END Menu Toggle -->
                            <li>
                                <a class="btn btn-primary" href="<?php echo $this->url('login');?>"><?php echo $this->translate('sign in'); ?></a>
                            </li>
                            <li>
                                <a class="btn btn-success" href="<?php echo $this->url('register');?>"><?php echo $this->translate('sign up'); ?></a>
                            </li>
                        </ul>
                        <!-- END Main Menu -->
                    </nav>
                    <!-- END Site Navigation -->
                </div>
            </header>
            <!-- END Site Header -->

            <?php echo $this->content; ?>
            
<!-- Modal -->
<div id="modal-privacy" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('Privacy Policy'); ?></h4>
            </div>
            <div class="modal-body">
                <?php echo $this->translate('privacy_policy_text'); ?>
            </div>
        </div>
    </div>
</div>

<div id="modal-terms" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('Terms & Conditions');?></h4>
            </div>
            <div class="modal-body">
                <?php echo $this->translate('terms_conditions_text'); ?>


            </div>
        </div>
    </div>
</div>

<section class="site-content site-section">
    <div class="container">
        <div class="row row-items text-center">
            <div class="col-sm-4 animation-fadeIn">
                <a href="javascript:void(0)" class="circle themed-background">
                <i class="fa fa-tachometer"></i>
                </a>
                <h4><?php echo $this->translate('Real Time Feedback'); ?></h4>
            </div>
            <div class="col-sm-4 animation-fadeIn">
                <a href="javascript:void(0)" class="circle themed-background">
                <i class="gi gi-stats"></i>
                </a>
                <h4><?php echo $this->translate('Custom Dashboards'); ?></h4>
            </div>
            <div class="col-sm-4 animation-fadeIn">
                <a href="javascript:void(0)" class="circle themed-background">
                <i class="gi gi-screenshot"></i>
                </a>
                <h4><?php echo $this->translate('Targeted Insight'); ?></h4>
            </div>
        </div>
        <div class="row row-items text-center">
            <div class="col-sm-4 animation-fadeIn">
                <a href="javascript:void(0)" class="circle themed-background">
                <i class="hi hi-cloud"></i>
                </a>
                <h4><?php echo $this->translate('Cloud Powered'); ?></h4>
            </div>
            <div class="col-sm-4 animation-fadeIn">
                <a href="javascript:void(0)" class="circle themed-background">
                <i class="gi gi-calendar"></i>
                </a>
                <h4><?php echo $this->translate('Scheduled Reports'); ?></h4>
            </div>
            <div class="col-sm-4 animation-fadeIn">
                <a href="javascript:void(0)" class="circle themed-background">
                <i class="gi gi-pie_chart"></i>
                </a>
                <h4><?php echo $this->translate('Highly Customizable'); ?></h4>
            </div>
        </div>
    </div>
</section>

                        
            <!-- Footer -->
            <footer class="site-footer site-section">
                <div class="container">
                    <!-- Footer Links -->
                    <div class="row">
                        <div class="col-sm-6 col-md-6">
                            <h4 class="footer-heading"><?php echo $this->translate('Legal'); ?></h4>
                            <ul class="footer-nav list-inline">
                                <li><a href="javascript:void(0)" data-toggle="modal" data-target="#modal-terms"><?php echo $this->translate('Terms & Conditions'); ?></a></li>
                                <li><a href="javascript:void(0)" data-toggle="modal" data-target="#modal-privacy"><?php echo $this->translate('Privacy Policy'); ?></a></li>
                            </ul>
                        </div>
                        <div class="col-sm-6 col-md-3 col-md-offset-3">
                            <h4 class="footer-heading"><span id="">2015</span> &copy; <a href="https://www.quickaudits.io">Quick Audits</a></h4>
                            <ul class="footer-nav list-inline">
                                <li><?php echo $this->translate('Developed by')?> <a href="https://www.quickaudits.io/" target="_blank">Quick Audits</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- END Footer Links -->
                </div>
            </footer>
            <!-- END Footer -->
        </div>
        <!-- END Page Container -->

        <!-- Include Jquery library from Google's CDN but if something goes wrong get Jquery from local file (Remove 'http:' if you have SSL) -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script>!window.jQuery && document.write(decodeURI('%3Cscript src="<?=$this->basePath('/modules/application/')?>js/vendor/jquery-1.11.1.min.js"%3E%3C/script%3E'));</script>

        <!-- Bootstrap.js, Jquery plugins and Custom JS code -->
        <script src="<?=$this->basePath('/modules/application/')?>js/vendor/bootstrap.min.js"></script>
        <script src="<?=$this->basePath('/modules/application/')?>js/plugins.js"></script>
        <script src="<?=$this->basePath('/modules/application/')?>js/app.js"></script>

        <!-- Load and execute javascript code used only in this page -->
        <script src="<?=$this->basePath('/modules/application/')?>js/pages/login.js"></script>
        <script>$(function(){ Login.init(); });</script>
    </body>
</html>