<?php $this->inlineScript()->captureStart(); ?>

$(function(){
    $('ul.sidebar-nav li ul li a.roles').addClass('active');
});

<?php $this->inlineScript()->captureEnd(); ?>

<div class="content-header">
    <div class="header-section">
        <h1>
            <i class="gi gi-nameplate"></i>Roles<br>
            <small>This is the default layout</small>
        </h1>
    </div>
</div>
<ul class="breadcrumb breadcrumb-top">
    <li>Home</li>
    <li><a href="">Roles</a></li>
</ul>