 <?php
 $form->prepare();
 ?>
<div class="block">
    <div class="block-title">
        <h2><strong>Edit </strong>new role</h2>
    </div>
    <?php 
     echo $this->form()->openTag($form);
     echo $this->formHidden($form->get('id'));
     ?>
    <div class="form-group">
        <label class="col-md-3 control-label">Name</label>
         <div class="col-md-9">
         <?php 
         echo $this->formInput($form->get('name'));
         ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('name'), array('class'=>'list-unstyled text-danger'))?></div>
         </div>
     </div>
     
     <?php $i = 0; ?>
     <?php while ($i < $permissions->count()) { ?>
     <?php $current =  $permissions->current(); ?>
     <?php $category = $current->category; ?>
     <fieldset>
        <legend><i class="fa fa-angle-right"></i> <?=$category?></legend>
        <div class="form-group">
            <label class="col-md-3 control-label">&nbsp;</label>
            <div class="col-md-9">
                <div class="col-md-9">
                    <?php while ($i < $permissions->count() && $category == $current->category) { ?>               
                    <div class="checkbox">
                        <label for="permissions_<?=$current->id?>">
                            <input  type="checkbox" 
                                    value="<?=$current->id?>" 
                                    name="permissions[]" 
                                    id="permissions_<?=$current->id?>" 
                                    <?php echo is_array($form->get('permissions')->getValue()) && in_array($current->id, $form->get('permissions')->getValue()) ? 'checked' : ''?> /> <?=$current->name?>
                        </label>
                    </div>
                    <?php $permissions->next(); ?>
                    <?php $current =  $permissions->current(); ?>
                    <?php $i++; ?>
                    <?php } ?>                
                </div>
            </div>
        </div>
    </fieldset>
    <?php } ?>
    
     
     <div class="form-group form-actions">
        <div class="col-md-9 col-md-offset-3">
            <?php echo $this->formSubmit($form->get('submit'));?>
        </div>
     </div>
     <?php
     echo $this->form()->closeTag();
     ?>
 </div>