 <?php
  $url = $this->url('admin/default', array(
    'controller'=>'role',
    'action' => 'index',
    'id'     => $this->id,
 ));
 ?>
  
 <div class="row">
	<div class="col-md-12">
		<!-- Info Block -->
		<div class="block">
			<!-- Info Title -->
			<div class="block-title">
				<h2><?=$this->escapeHtml($role->name)?></h2>
			</div>
			<!-- END Info Title -->

			<!-- Info Content -->
			<table class="table table-borderless table-striped">
				<tbody>
					<tr>
						<td style="width: 20%;"><strong>Nombre</strong></td>
						<td><?=$this->escapeHtml($role->name)?></td>
					</tr>
					<tr>
						<td style="width: 20%;"><strong>Activo</strong></td>
						<td><?=$role->active ? 'Sí' : 'No'?></td>
					</tr>
					
				</tbody>
			</table>
			<!-- END Info Content -->
		</div>

		<div class="block">
			<div class="row">
				<div class="col-md-12">
					<a href="/admin/role/edit/<?=$role->id?>" class="btn btn-sm btn-primary">Editar</a>
					<a href="/admin/role" class="btn btn-sm btn-warning">Volver al Listado</a>
					<div class="clearfix">&nbsp;</div>
				</div>
			</div>
        </div>        
	</div>
</div>