 <?php
 $form->prepare();
?>
<div class="block">
    <div class="block-title">
        <h2><strong>Edit </strong>new user</h2>
    </div>
    <?php 
     echo $this->form()->openTag($form); 
     echo $this->formHidden($form->get('id'));
     ?>
     <div class="form-group">
        <label class="col-md-3 control-label">First name</label>
         <div class="col-md-9">
         <?php 
         echo $this->formInput($form->get('firstname'));
         ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('firstname'), array('class'=>'list-unstyled text-danger'))?></div>
         </div>
     </div>
     <div class="form-group">
        <label class="col-md-3 control-label">Last name</label>
         <div class="col-md-9">
         <?php 
         echo $this->formInput($form->get('lastname'));
         ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('lastname'), array('class'=>'list-unstyled text-danger'))?></div>
         </div>
     </div>
     <div class="form-group">
        <label class="col-md-3 control-label">Email</label>
         <div class="col-md-9">
         <?php 
         echo $this->formInput($form->get('email'));
         ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('email'), array('class'=>'list-unstyled text-danger'))?></div>
         </div>
     </div>
     <div class="form-group">
        <label class="col-md-3 control-label">Role</label>
         <div class="col-md-9">
         <?php 
         echo $this->formselect($form->get('id_role'));
         ?>
            <div class="help-block"><?=$this->formElementErrors($form->get('id_role'), array('class'=>'list-unstyled text-danger'))?></div>
         </div>
     </div>
     <div class="form-group form-actions">
        <div class="col-md-9 col-md-offset-3">
            <?php echo $this->formSubmit($form->get('submit'));?>
        </div>
     </div>
     <?php
     echo $this->form()->closeTag();
     ?>
 </div>