<div class="block">

    <div class="block-section">
        <p class="text-center text-success"><i class="fa fa-check-circle fa-5x"></i></p>
        <h3 class="text-center"><strong><?php //echo $this->translate('Thank you for your evaluation!')?></strong></h3>
<!--         <br/> -->
<!--         <h5 class="text-center"><strong>Don't forget to share this evaluation with your friends and colleagues</strong></h5> -->
<!--         <br/> -->
<!--         <p class="text-center"> -->
<!--             <span class='st_facebook_large' displayText='Facebook'></span> -->
<!--             <span class='st_twitter_large' displayText='Tweet'></span> -->
<!--             <span class='st_linkedin_large' displayText='LinkedIn'></span> -->
<!--             <span class='st_email_large' displayText='Email'></span> -->
<!--         </p> -->
    </div>

</div>
<!-- 
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "af7605b1-8658-42b1-9e2a-af96a1d47fb7", doNotHash: false, doNotCopy: false, hashAddressBar: true});</script>
-->