<div class="row">
	<div class="col-md-12">
		<!-- Widget -->
		<div class="widget">
			<div class="widget-extra-full text-center themed-background-spring">
                <?php if ($this->layout()->getVariable('role')->hasPermission('organization_manage-dashboard')) {?>
                <div class="widget-options">
        					<div class="btn-group btn-group-xs">
        						<a
        							data-original-title="<?php echo $this->translate('Manage Dashboards'); ?>"
        							href="<?php echo $this->url('application/default', array('controller'=>'organization','action'=>'manage-dashboard'));?>"
        							class="btn btn-xs btn-default" data-toggle="tooltip"
        							title="<?php echo $this->translate('Manage Dashboards'); ?>"><i
        							class="fa fa-cog"></i></a>
        					</div>
        				</div>    
                <?php } ?>
				<h3 class="widget-content-light">
					Satisfacción del Cliente<br><small>Mes en curso</small>
				</h3>
			</div>
			<div class="widget-simple">
				<div class="row text-center">
				    <?php foreach ($cs as $score) {
                        $por =  $score['score']/ $score['samples']*100;
                      ?>
					<div class="col-md-2">						
						<div class="animation-fadeIn">
        					<div class="customer-satisfaction"
        						data-percent="<?= $por ?>"
        						data-size="100"
        						data-bar-color="<?= $por >= $score['min_performance_required'] ? '#27ae60' : '#e11b1b'; ?>">
        						<span><?= number_format($por, 2); ?>%</span>
        					</div>
        				</div>
						<h3><small><?= $score['question'] ?></small></h3>
					</div>
					
					<?php } ?>
				</div>
			</div>
		</div>
		<!-- END Widget -->
	</div>


</div>

<script type="text/javascript">
<!--

$(function(){

        $('.customer-satisfaction').easyPieChart({
            barColor: $(this).data('bar-color') ? $(this).data('bar-color') : '#777777',
            trackColor: $(this).data('track-color') ? $(this).data('track-color') : '#eeeeee',
            lineWidth: $(this).data('line-width') ? $(this).data('line-width') : 3,
            size: $(this).data('size') ? $(this).data('size') : '80',
            animate: 800,
            scaleColor: false
        });

});

//-->
</script>
<script type="text/javascript">
<!--
$(function(){
$('[data-toggle="tooltip"], .enable-tooltip').tooltip({container: 'body', animation: false});
});
//-->
</script>