<div class="row">
	<div class="col-md-12">
		<!-- Widget -->
		<div class="widget">
			<div class="widget-extra-full text-center themed-background-spring">
                <?php if ($this->layout()->getVariable('role')->hasPermission('organization_manage-dashboard')) {?>
                <div class="widget-options">
        					<div class="btn-group btn-group-xs">
        						<a
        							data-original-title="<?php echo $this->translate('Manage Dashboards'); ?>"
        							href="<?php echo $this->url('application/default', array('controller'=>'organization','action'=>'manage-dashboard'));?>"
        							class="btn btn-xs btn-default" data-toggle="tooltip"
        							title="<?php echo $this->translate('Manage Dashboards'); ?>"><i
        							class="fa fa-cog"></i></a>
        					</div>
        				</div>    
                <?php } ?>
				<h3 class="widget-content-light">
					<?php echo $this->translate('Today\'s score per project'); ?>
				</h3>
			</div>
			<div class="widget-simple">
				<div class="row text-center">
				    <?php foreach ($todayScore as $score) { ?>
					<div class="col-md-2">
						
						<div class="animation-fadeIn">
        					<div class="pie-chart-mtd-score"
        						data-percent="<?php echo $todayScore->current()->score; ?>"
        						data-size="100"
        						data-bar-color="<?php echo $todayScore->current()->score >= $todayScore->current()->min_performance_required ? '#27ae60' : '#e11b1b'; ?>">
        						<span><?php echo number_format($todayScore->current()->score, 2); ?>%</span>
        					</div>
        				</div>
						
						<h3><small><?php echo $todayScore->current()->project; ?></small></h3>
					</div>
					
					<?php } ?>
				</div>
			</div>
		</div>
		<!-- END Widget -->
	</div>


</div>

<script type="text/javascript">
<!--

$(function(){

        $('.pie-chart-mtd-score').easyPieChart({
            barColor: $(this).data('bar-color') ? $(this).data('bar-color') : '#777777',
            trackColor: $(this).data('track-color') ? $(this).data('track-color') : '#eeeeee',
            lineWidth: $(this).data('line-width') ? $(this).data('line-width') : 3,
            size: $(this).data('size') ? $(this).data('size') : '80',
            animate: 800,
            scaleColor: false
        });

});

//-->
</script>
<script type="text/javascript">
<!--
$(function(){
$('[data-toggle="tooltip"], .enable-tooltip').tooltip({container: 'body', animation: false});
});
//-->
</script>